### ISSUE TITLE
Running the server after install

### ISSUE THREAD

**Issue by Katakeyni** [Limenius/symfony-react-sandbox#13] opened 2016-09-29 14:19 UTC
Hii 
I have installed the bundle and after composer install and npm install I got the message **Server bundle not found**. 

![capture d ecran 2016-09-29 a 14 08 04](https://cloud.githubusercontent.com/assets/6898114/18957669/79f171ce-864f-11e6-82e1-b6928ba4fd62.png)

I've created the file in app/Resources/webpack but still get the same error. What should I do ?
Thank you

**Comment by Koalabaerchen** [comment] 2016-10-13 14:19
The problem comes from nacmartin/phpexecjs and has been fixed in https://github.com/nacmartin/phpexecjs/commit/4b95e346f589d5e67bd4ce15cec73ae50eb40a16

The problem is that there is no release for it yet and the sandbox doesn't like dev-master.

**Comment by nacmartin** [comment] 2016-10-13 17:43
There is a release now, and composer.lock has been updated. Thanks for reporting!

**Closed** 2016-10-13 17:43 UTC
