### ISSUE TITLE
Symfony Roles

### ISSUE THREAD

**Issue by tylerm22** [Limenius/symfony-react-sandbox#19] opened 2017-02-07 15:48 UTC
i am trying to check if is_granted in the react code to check Symfony roles assigned to a user to see if the user can add a recipe or not, but I can't figure out how. Is there an easy way to do this or will this be needing any additional API parameters?!

**Comment by nacmartin** [comment] 2017-02-08 11:14
The React code has no access to the user or security mechanisms of Symfony, as it would be the case in any other API based client, such as iOS or Android apps. You have several options here, like passing as props if the user has a specific role, or use https://github.com/lexik/LexikJWTAuthenticationBundle for authentication, and inspecting the token to check the granted claims... or any other mechanism. Don't forget to secure your endpoints also in the server-side.

I am closing this issue as this is not a bug of this project, but a general question.

**Closed by nacmartin** 2017-02-08 11:14 UTC
