### ISSUE TITLE
webpack-dev-server hot reload not working

### ISSUE THREAD

**Issue by avg0043** [Limenius/symfony-react-sandbox#26] opened 2017-02-17 15:09 UTC
Hi,
I have cloned the project and I run it using the following commands:

1. npm run webpack-serverside
2. npm run webpack-dev
3. bin/console server:start

After this, I visit http://localhost:8000/ and shows the web perfectly.
Problem comes when I change a Javascript file:

1. Terminal doesn't rebuild this change
2. And the change doesn't appears on browser

Why **hot-reload** doesn't works? Where is my problem?

Thanks.

**Comment by nacmartin** [comment] 2017-02-19 13:32
Thanks for reporting this. This is interesting, does it recompute the changes, though? I mean, if you reload manually the page the changes in JS are reflected? can you tell me a bit more about your OS, browser so I can work on reproducing the error?

**Comment by avg0043** [comment] 2017-02-20 09:32
If I reload manually the page it happens the same, no changes are reflected on browser.
It's really strange because this morning when I have run the project by first time, the changes have been being reflected on browser but when I stop all and run it again, it has come back to the same error.. :(

I'm using Ubuntu 16.04 LTS and Google Chrome Versión 54.0.2840.100 (64-bit).

**Comment by VictoriaQ** [comment] 2017-02-23 18:09
Hi! I have just downloaded the project, followed the instructions as you did, and everything works as expected -automatic reload included. They OS I'm using is exactly the same as you. Perhaps you could check if Webpack is behaving correctly for you in some other project... The reason might be something external, not related to the sandbox.

I'm closing this because I cannot reproduce it, but if someone else has the same issue, it can be reopened.

**Closed by VictoriaQ** 2017-02-23 18:09 UTC
