### ISSUE TITLE
DB modifications not refreshing object

### ISSUE THREAD

**Issue by ralmeidaLink** [Limenius/symfony-react-sandbox#31] opened 2017-05-05 08:44 UTC
I'll explain the process starting in the beginning of all hoping to get an answer.

First of all, can I get a more specif explanation about the server-side and client-side? For my readings till here, doesn't react render views? If so, why having a server side?

Then, a more concrete example about this project. I can install it with no problems and also run it. After I run it. When I first enter the homepage it brings me all the recipes (i could see in the ajax request). Lets say I do alter some recipe in the db. When I enter that specific recipe (showAction for the say) I can see the modifications I made, but when I do come back for the homepage (not back button nor F5 to refresh) it shows all the recipes, but the recipe i've modify still is the old one, without the changes. Can I get an explanation about this?

Thanks in advance

**Comment by nacmartin** [comment] 2017-05-05 13:26
Hi, I read the issues posted here. Note that there is no need to write me to my personal email with a duplicate of the issue, as I already receive these notifications by email. 

I am working now, I'll try to allocate some time to answer properly later on, or during the weekend.

Anyways, you tell me in your email that you are starting with React. Note that there is no need to use this sandbox, bundle, or any other extra code to use React with Symfony. Here we just did a showcase of several things that may help you integrate your code with Symfony in case you need, for instance, server-side rendering (which many projects don't need at all), a Twig integration (that is syntactic sugar), or what we think is a better integration with Symfony forms so you don't need to write forms twice in Sf and React. There is also some sample of React code that you may want to look at, but it is completely optional.

I will check out later the case that you are describing.

**Comment by nacmartin** [comment] 2017-05-28 16:17
I have trying to reply the bug, but I cannot. The only thing that may be confusing is that when you go back to the home page, the results are added at the end (there is no sorting applied to the underlying doctrine queries). It would be interesting to know if the new objects are added to the database or not, to be able to find the cause of your problem.

**Closed** 2017-06-09 13:19 UTC
